name: python38llava
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - jpeg=9e=h5eee18b_3
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libwebp-base=1.3.2=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.4=h6a678d5_0
  - ninja-base=1.12.1=hdb19cb5_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.16=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.20=he870216_0
  - pytorch-cuda=11.7=h778d358_5
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.1
      - accelerate==0.21.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - altair==5.4.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.5.2
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==12.3.0
      - backcall==0.2.0
      - bert-score==0.3.13
      - bitsandbytes==0.41.0
      - blinker==1.8.2
      - blis==0.7.11
      - braceexpand==0.1.7
      - cachetools==5.5.2
      - catalogue==2.0.10
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.8
      - cmake==3.25.0
      - comm==0.2.2
      - confection==0.1.5
      - configargparse==1.7.1
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - cymem==2.0.11
      - dash==3.1.1
      - datasets==3.1.0
      - debugpy==1.8.15
      - decorator==4.4.2
      - decord==0.6.0
      - deepspeed==0.9.5
      - diffusers==0.34.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - easydict==1.13
      - einops==0.6.1
      - einops-exts==0.0.4
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fairscale==0.4.13
      - fastapi==0.115.12
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.13.1
      - flash-attn==2.3.2
      - flask==3.0.3
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - ftfy==6.2.3
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - gradio==3.35.2
      - gradio-client==0.2.9
      - grpcio==1.70.0
      - h11==0.14.0
      - h5py==3.11.0
      - hf-xet==1.1.2
      - hjson==3.1.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.23.0
      - idna==3.4
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iopath==0.1.10
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - langcodes==3.4.1
      - language-data==1.3.0
      - lazy-loader==0.4
      - linkify-it-py==2.0.3
      - lit==15.0.7
      - llava==1.1.3
      - marisa-trie==1.2.1
      - markdown==3.7
      - markdown-it-py==2.2.0
      - markdown2==2.5.1
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - narwhals==1.40.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.0
      - ninja==1.11.1.4
      - nltk==3.8.1
      - numpy==1.24.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python==4.12.0.88
      - optree==0.15.0
      - orjson==3.10.15
      - packaging==25.0
      - pandas==2.0.3
      - parso==0.8.4
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - peft==0.4.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.2.0
      - portalocker==3.0.0
      - preshed==3.0.10
      - proglog==0.1.12
      - progressbar2==4.5.0
      - prompt-toolkit==3.0.51
      - propcache==0.2.0
      - protobuf==5.29.4
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pydantic==1.10.22
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pynvml==11.5.3
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - python-utils==3.8.2
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.11
      - rank-bm25==0.2.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - retrying==1.4.1
      - rich==14.0.0
      - rouge-score==0.1.2
      - rpds-py==0.20.1
      - rsa==4.9.1
      - ruff==0.11.11
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.2
      - six==1.17.0
      - smart-open==6.4.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - spacy==3.5.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - stack-data==0.6.3
      - starlette==0.44.0
      - svgwrite==1.4.3
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - thinc==8.1.12
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tiktoken==0.7.0
      - timm==0.6.13
      - tokenizers==0.13.3
      - tomlkit==0.12.0
      - torch==2.0.1+cu117
      - torchaudio==2.0.2+cu117
      - torchinfo==1.8.0
      - torchvision==0.15.2+cu117
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.31.0
      - transformers-stream-generator==0.0.5
      - triton==2.0.0
      - trl==0.8.6
      - typeguard==4.4.0
      - typer==0.9.4
      - typing-extensions==4.13.2
      - tyro==0.9.26
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - ujson==5.10.0
      - urllib3==1.26.13
      - uvicorn==0.33.0
      - visual-genome==1.1.1
      - wandb==0.19.11
      - wasabi==1.1.3
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - webdataset==0.2.100
      - websockets==11.0.3
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - xxhash==3.5.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /data/users/zhuhaoran/.conda/envs/python38llava
